branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - develop
language: minimal
jobs:
  include:
    - os: osx
      osx_image: xcode12.4
      before_install:
        - brew tap adoptopenjdk/openjdk
        - brew install --cask adoptopenjdk11
        - brew install esolitos/ipa/sshpass
        - brew install maven
        - rm ~/.m2/settings.xml
    - os: windows
      before_install:
        - choco install adoptopenjdk11
        - choco install maven
        - choco install putty
        - export PATH=$(cmd.exe //c "refreshenv > nul & C:\Progra~1\Git\bin\bash -c 'echo \$PATH'")
install:
  - mvn dependency:go-offline -B
script:
  - mvn test -B
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mvn clean package -DskipTests -P mac -B      ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mvn clean package -DskipTests -P win -B  ; fi
before_deploy:
  - export MAC_FILE_PATH=target/PdfTrick_${TRAVIS_TAG:1}.dmg
  - export WIN_FILE_PATH=target/PdfTrick_${TRAVIS_TAG:1}.exe
deploy:
  #- provider: script
    #skip_cleanup: true
    #script: bash ./deploy.sh
    #on:
      #branch: develop
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file:
      - $MAC_FILE_PATH
      - $WIN_FILE_PATH
    skip_cleanup: true
    on:
      tags: true
